import Head from "next/head";

import { FileDataProvider } from "@/context/global-context";

import HomePage from "@/components/HomePage/home-page";
import HomeChunks from "@/components/alt/home-page-chunks";
// import HomePageAlt from "@/components/alt/home-page-alt";

export default function Home() {
  return (
      <>
        <Head>
          <title>File Processor</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.jpg"/>
        </Head>

        <FileDataProvider>
          <HomeChunks />
        </FileDataProvider>
      </>
  );
}